transfer files to server

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,17 +1,28 @@
 #!/usr/bin/env bash
-# Transfers a file from our client to a server.
-#
-# The script accepts 4 parameters:
-# 	- The path to the file to be transferred.
-#	- The IP of the server we want to transfer the file to
-#	- The username scp connects with
-#	- The path to the SSH private key that scp uses
-#
+# checking for command line arguments
 
-if [ "$4" ] ; then
-	scp -i "$4" -o StrictHostKeyChecking=no "$1" "$3@$2:~"
-elif [ "$3" ] ; then
-	scp -o StrictHostKeyChecking=no "$1" "$3@$2~"
-else
+if [ $# -lt 4 ]
+then
 	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+	exit 1
+fi
+
+# assigning parameters to variables
+
+path_to_file=$1
+ip=$2
+username=$3
+path_to_ssh_key=$4
+
+# disabling strict host key checking
+
+scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+
+
+# checking if the transfer was successful
+if [ $? -eq 0 ]
+then
+	echo "FILE WAS TRANSFERRED SUCCESSFULLY"
+else
+	echo "FILE TRANSFER FAILED"
 fi
